export { Catalog } from './catalog/components/catalog'
export { NotFount } from './notFound/index'
export { Main } from './main/components/index'
export { Contact } from './Contact/imdex'
export { DetailProduct } from './DetailsProduct/index'
